version: 3.0.0
services:
  postgres:
    image: postgres:9.6
    env_file:
      - ./postgres/.env
    ports:
      - "5432:5432"
    volumes:
      - ./postgres/data/postgres:/var/lib/postgresql/data
    restart: always
    networks:
      app_network:
        ipv4_address: 192.168.0.2
        aliases:
          - "postgres_db"
  pgadmin:
    image: dpage/pgadmin4
    env_file:
      - ./pgadmin/.env
    ports:
      - "80:80"
    volumes:
      - ./pgadmin/data/pgadmin:/var/lib/pgadmin
    restart: always
    networks:
      app_network:
        ipv4_address: 192.168.0.3
        aliases:
          - "pgadmin"
    depends_on:
      - postgres
networks:
  app_network:
    ipam:
      driver: default
      config:
        - subnet: "192.168.0.0/24"
          gateway: 192.168.0.1